version: "4.2"

services:
  mongodb:
    container_name: mongo.db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongodb/data
    networks:
      - quiz_app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Admin@123$
  sqlserver:
    container_name: sqlserver.db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/lib/sqlserver/data
    networks:
      - quiz_app
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123$

networks:
  quiz_app:
    driver: bridge
volumes:
  mongo-data:
  sqlserver-data:
